homeassistant:

  #-------------------------------------------
#  auth_providers:
#   - type: legacy_api_password
#     api_password: !secret http_password
  #-------------------------------------------
  packages: !include_dir_named packages



#-------------------------------------------
# HTTP Server Config
#-------------------------------------------
http:
#  api_password: !secret http_password
#  ssl_certificate: /home/homeassistant/.homeassistant/certificate.pem
#  ssl_key: /home/homeassistant/.homeassistant/privkey.pem

  # Secrets are defined in the file secrets.yaml
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

automation:

 
config:
# Frontend Settings
#-------------------------------------------
frontend:
  themes: !include_dir_merge_named themes
#-------------------------------------------

# History support
#-------------------------------------------
history: !include history.yaml

# Logbook Settings
#-------------------------------------------
logbook: !include logbook.yaml
system_log:
  max_entries: 500
  
# Enables a map showing the location of tracked devices
#-------------------------------------------

#-------------------------------------------
system_health:

# Checks for available updates
#-------------------------------------------
updater:
  reporting: False
  # Optional, allows Home Assistant developers to focus on popular components.
#  include_used_components: true


# Recorder Settings
#-------------------------------------------
recorder:  !include recorder.yaml
#-------------------------------------------

#history_graph: !include history_graph.yaml
#-------------------------------------------

# Browser
#-------------------------------------------
browser:
#-------------------------------------------

#-------------------------------------------
mqtt:
  broker: 10.10.0.14
  port: 1883
  client_id: home-zwave
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_pwr

#  certificate: /config/ca.crt
  birth_message:
    topic: 'hasszwave/status'
    payload: "online"
    qos: 1
    retain: true
  will_message:
    topic: 'hasszwave/status'
    payload: "offline"
    qos: 1
    retain: true 
 
mqtt_statestream:
  base_topic: hasszwave
  include:
    domains:
      - sensor
      - cover
      - climate
      - switch
     

# Panel settings
#-------------------------------------------
panel_iframe: !include panels.yaml
#-------------------------------------------
panel_custom:
  - name: zwavegraph2
    sidebar_title: ZWave Graph2
    sidebar_icon: mdi:access-point-network
    url_path: zwave

zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 600000




