homeassistant:
  name: home
  # Location required to calculate the time the sun rises and sets
  latitude:  !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 54
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  # Include customizations
  #-------------------------------------------
  #-------------------------------------------
  packages: !include_dir_named packages
  customize: !include customize.yaml

# Enable configuration UI
#-------------------------------------------
config:
#-------------------------------------------

# Frontend Settings
#-------------------------------------------
#frontend:
#  javascript_version: latest
#  themes: !include themes.yaml
#-------------------------------------------

# Logger Settings
#-------------------------------------------
#logger: !include logger.yaml
#-------------------------------------------

  
# Logbook Settings
#-------------------------------------------
logbook: !include logbook.yaml
system_log:
  max_entries: 500
#-------------------------------------------

# Recorder Settings
#-------------------------------------------
recorder:  !include recorder.yaml
#-------------------------------------------

# History support
#-------------------------------------------
history: !include history.yaml

#history_graph: !include history_graph.yaml
#-------------------------------------------

# Checks for available updates
#-------------------------------------------
updater:
  reporting: False
  # Optional, allows Home Assistant developers to focus on popular components.
#  include_used_components: true
#-------------------------------------------

# Zeroconf
#-------------------------------------------
zeroconf:
#-------------------------------------------

# Browser
#-------------------------------------------
browser:
#-------------------------------------------

# HTTP Server Config
#-------------------------------------------
http:
#  api_password: !secret http_password
#  ssl_certificate: /home/homeassistant/.homeassistant/certificate.pem
#  ssl_key: /home/homeassistant/.homeassistant/privkey.pem

  # Secrets are defined in the file secrets.yaml
  #api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#-------------------------------------------


# Allows you to issue voice commands from the frontend in enabled browsers
#-------------------------------------------
conversation:
  intents:
    ShoppingListAddItem:
      - Add {item} to my shopping list
      
#-------------------------------------------


# Enables a map showing the location of tracked devices
#-------------------------------------------
map:
#-------------------------------------------

# Pilight 433 MHz Empfänger
#-------------------------------------------
#pilight:
#  host: pi-hass.fritz.box
#  port: 5000
#  send_delay: 0.4
#  whitelist:  # optional
#    protocol:
#      - daycom
#      - intertechno
#    id:
#      - 42
#-------------------------------------------

#-------------------------------------------
#remote:
#  - platform: harmony
#    name: Wohnzimmer
#    activity: Fernsehen
emulated_roku:
  host_ip: 127.0.0.1 # should be set to Home Assistant's address
#  advertise_ip: 10.0.0.10 # optional, defaults to host_ip if not specified
  upnp_bind_multicast: True # optional, defaults to True
  listen_ports:
    - 8060
#    - 8061:8080 # optional format when using something like Docker - port:advertise_port

 #-------------------------------------------

#MQTT
#-------------------------------------------
mqtt:
  broker: 10.10.0.4
  username: !secret mqtt_user
  password: !secret mqtt_pwr
  birth_message:
    topic: "/home/tele/hass1/LWT"
    payload: "online"
    qos: 1
    retain: true
  will_message:
    topic: "/home/tele/hass1/LWT"
    payload: "offline"
    qos: 1
    retain: true 
  discovery: true
  discovery_prefix: homeassistant
  
mqtt_statestream:
  base_topic: homeassistant
  exclude:
    domains:
      - group
      - media_player
      - device_tracker
      - script
      - calendar
      - script
      - weather
      - sun
      
 
 
#  certificate: /home/pi/client.crt
#-------------------------------------------

# Track the sun
#-------------------------------------------
sun:
weather:
  - platform: openweathermap
    api_key: !secret openweathermap
    latitude: !secret latitude
    longitude: !secret longitude
    forecast: true
#-------------------------------------------

# Discovery suche im Netzwerk
#-------------------------------------------
discovery:
#  ignore:
#    - home_assistant
#    - samsung_tv
#-------------------------------------------

#
#-------------------------------------------
input_number: !include input_number.yaml
#-------------------------------------------
#

# CEC support
#-------------------------------------------
#hdmi_cec:  !include cec.yaml
#-------------------------------------------

# Camera support
#-------------------------------------------
camera: !include camera.yaml
#-------------------------------------------

# Text to speech settings
#-------------------------------------------
#tts:
#  - platform: google
#    language: 'de'
#-------------------------------------------

# Panel settings
#-------------------------------------------
panel_iframe: !include panels.yaml
#-------------------------------------------

# Shopping support
#-------------------------------------------
shopping_list:
#-------------------------------------------

# Tracer support
#-------------------------------------------
device_tracker: !include device_tracker.yaml
#-------------------------------------------

# Media Players
#-------------------------------------------
#media_player: !include mediaplayer.yaml
#-------------------------------------------

#-------------------------------------------
#google:
#  client_id: !secret google_client_id
#  client_secret: !secret google_client_secret
#-------------------------------------------

#-------------------------------------------
#switch: !include switches.yaml
#-------------------------------------------

# Include sensors
#-------------------------------------------
#sensor: !include_dir_merge_list sensors
#-------------------------------------------

# Include sensors
#-------------------------------------------
#binary_sensor: !include_dir_merge_list binary_sensors
#-------------------------------------------

#-------------------------------------------
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - 470666005
notify:
  - name: Wolfhome
    platform: telegram
    chat_id: 470666005
#-------------------------------------------


# Scripts
#-------------------------------------------
#script: !include scripts.yaml
#-------------------------------------------

# Weblinks
#-------------------------------------------
#weblink: !include weblink.yaml
weblink:
  entities:
#    - name: Fritz Box 7590
#      url: http://fritz.box/
#      icon: mdi:ethernet
    - name: Fritz Box 7390
      url: http://10.10.10.11/
      icon: mdi:ethernet

    - name: Nas3 Web
      url: http://10.10.0.4:5000
      icon: mdi:security-network

    - name: Wolfgang da2 Web
      url: http://wolfgang-da2.fritz.box:8080
      icon: mdi:security-network

    - name: Radio Schalter Küche Web
      url: http://r-schalter.fritz.box
      icon: mdi:security-network

    - name: Licht Keller Flur Web
      url: http://LKellerFlur.fritz.box
      icon: mdi:security-network

    - name: Radio Schalter Keller Web
      url: http://r-schalter1.fritz.box
      icon: mdi:security-network

    - name: Licht Schalter Aquarium Web
      url: http://aquarium.fritz.box
      icon: mdi:security-network

    - name: Speicher Schalter Basteln Web
      url: http://speicher-basteln.fritz.box
      icon: mdi:security-network

    - name: Licht Treppe Speicher Web
      url: http://LTreppeOben.fritz.box
      icon: mdi:security-network

    - name: Lade Schalter Vorrat Web
      url: http://l-schalter-vor.fritz.box
      icon: mdi:security-network

#-------------------------------------------

# Include automations
#-------------------------------------------
#automation: !include_dir_merge_list automations
#-------------------------------------------

# Include groups
#-------------------------------------------
#group: !include_dir_merge_named groups
#-------------------------------------------

