resources:
- type: js
  url: /community_plugin/monster-card/monster-card.js
- type: module
  url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
- type: module
  url: /community_plugin/simple-thermostat/simple-thermostat.js
- type: module
  url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
- type: module
  url: /community_plugin/entity-attributes-card/entity-attributes-card.js
- type: js
  url: /customcards/theme-maker.js
- type: module
  url: /community_plugin/lovelace-card-tools/card-tools.js
- type: js
  url: /customcards/custom-lovelace/card-modder.js
- type: module
  url: /customcards/atomic-calendar.js
title: home
views:
- badges: []
  cards:
  - entities:
    - entity: sensor.installed_version
    - entity: input_select.theme_select
    show_header_toggle: false
    title: Informationen
    type: entities
  - card:
      show_header_toggle: false
      title: Z Wave
      type: entities
    filter:
      include:
      - domain: zwave
    show_empty: false
    type: custom:monster-card
  - entities:
    - entity: sensor.hass_uptime
    - entity: sensor.ha_version
    - entity: sensor.installed_version
    - entity: input_select.log_level
    - entity: binary_sensor.updater
    show_header_toggle: false
    title: Home Assistant Info
    type: entities
  icon: mdi:home
  path: default_view
  title: default_view
- badges: []
  cards:
  - elements:
    - entity: sensor.heizen_flur_temperature
      style:
        left: 52%
        top: 60%
      type: state-label
    image: /local/Keller.jpg
    type: picture-elements
  - entity: climate.heizen_flur_heating
    sensors:
    - entity: sensor.buro_temperatur
    step_size: 0.5
    type: custom:simple-thermostat
  - entities:
    - entity: switch.wlan_switch
    - entity: sensor.wlan_current
    - entity: sensor.wlan_energy
    - entity: sensor.wlan_power
    - entity: sensor.wlan_voltage
    - entity: sensor.wlan_previous_reading
    - entity: zwave.wlan
    type: entities
  icon: mdi:stairs
  path: g_keller
  title: Keller
- badges: []
  cards:
  - entities:
    - entity: sensor.vorne_strahler_luminance
    - entity: sensor.hinten_strahler_luminance
    - entity: sensor.eingang_strahler_luminance
    hours_to_show: 168
    name: Licht
    points_per_hour: 0.25
    show:
      extrema: true
      labels: true
    type: custom:mini-graph-card
  - entities:
    - entity: switch.eingang_strahler_switch
    - entity: sensor.eingang_strahler_burglar_1
    - entity: switch.hinten_strahler_switch
    - entity: sensor.hinten_strahler_burglar_1
    - entity: switch.vorne_strahler_switch
    - entity: sensor.vorne_strahler_burglar_1
    - entity: sensor.luminance
    - entity: switch.pool_pumpe_switch
    show_header_toggle: false
    title: Licht Aussen
    type: entities
  - entities:
    - entity: sensor.eingang_strahler_luminance
    - entity: sensor.hinten_strahler_luminance
    - entity: sensor.vorne_strahler_luminance
    show_header_toggle: false
    title: Sensor Aussen
    type: entities
  icon: mdi:nature
  path: g_aussen
  title: Aussen
- badges: []
  cards:
  - elements:
    - entity: sensor.heizen_fenster_temperature
      style:
        left: 20%
        top: 54%
      type: state-label
    - entity: sensor.wohnzimmer_heizung_sofa_temperature
      style:
        left: 55%
        top: 22%
      type: state-label
    - entity: sensor.heizen_treppe_temperature
      style:
        left: 50%
        top: 50%
      type: state-label
    - entity: sensor.heizen_eingang_temperature
      style:
        left: 48%
        top: 85%
      type: state-label
    image: /local/unten.jpg
    type: picture-elements
  - entity: climate.heizen_treppe_heat
    sensors:
    - entity: sensor.vorrat_temperatur
    - entity: sensor.heizen_eingang_temperature
    step_size: 1
    type: custom:simple-thermostat
  - entity: climate.heizen_eingang_heat
    sensors:
    - entity: sensor.vorrat_temperatur
    - entity: sensor.heizen_treppe_temperature
    step_size: 1
    type: custom:simple-thermostat
  - entities:
    - entity: sensor.vorrat_temperatur
      line_color_above:
      - color: yellow
        value: 17
      - color: orange
        value: 20
      - color: red
        value: 22
    - entity: sensor.heizen_eingang_temperature
    - entity: sensor.heizen_treppe_temperature
    - entity: sensor.heizen_fenster_temperature
    - entity: sensor.wohnzimmer_heizung_sofa_temperature
    hours_to_show: 240
    name: Temperatur
    points_per_hour: 0.25
    show:
      extrema: true
      labels: true
    type: custom:mini-graph-card
  path: g_unten
  title: Unten
- badges: []
  cards:
  - cards:
    - entities:
      - entity: sensor.kaffee_power
      hours_to_show: 24
      points_per_hour: 0.5
      show:
        extrema: true
        labels: true
      type: custom:mini-graph-card
    - entities:
      - switch.kaffee_switch
      - head: sensor.kaffee_energy
        items:
        - zwave.kaffee_power
        type: custom:fold-entity-row
      show_header_toggle: false
      type: entities
    type: vertical-stack
  - entity: climate.heizen_kueche_heating
    sensors:
    - entity: sensor.kuche_temperatur
    step_size: 0.5
    type: custom:simple-thermostat
  icon: mdi:food-fork-drink
  path: g_kueche
  title: kueche
- badges: []
  cards:
  - entity: climate.heizen_fenster_heat
    sensors:
    - entity: sensor.wohnzimmer_temperatur
    - entity: sensor.wohnzimmer_heizung_sofa_temperature
    step_size: 0.5
    type: custom:simple-thermostat
  - entity: climate.wohnzimmer_heizung_sofa_heat
    sensors:
    - entity: sensor.wohnzimmer_temperatur
    - entity: sensor.heizen_fenster_temperature
    step_size: 0.5
    type: custom:simple-thermostat
  - cards:
    - cards:
      - entities:
        - head: sensor.wohnzimmer_aquarium_energy
          items:
          - zwave.aquarium_power
          - sensor.wohnzimmer_aquarium_power_2
          - sensor.wohnzimmer_aquarium_alarm_type
          - sensor.wohnzimmer_aquarium_alarm_level
          - input_number.auto_aquarium_offset_on
          - input_number.auto_light_offset_off
          type: custom:fold-entity-row
        show_header_toggle: false
        type: entities
      - cards:
        - entity: switch.wohnzimmer_aquarium_switch
          hold_action:
            action: none
          tap_action:
            action: toggle
          type: entity-button
        type: vertical-stack
      title: Switches
      type: horizontal-stack
    - entities:
      - entity: sensor.wohnzimmer_aquarium_power
      hours_to_show: 240
      points_per_hour: 0.25
      show:
        extrema: true
        labels: true
      type: custom:mini-graph-card
    type: vertical-stack
  - entities:
    - entity: zwave.wohnzimmer_heizung_sofa
    - entity: zwave.heizen_fenster
    show_header_toggle: false
    title: Heizung
    type: entities
  icon: mdi:sofa
  path: g_wohnzimmer
  title: Wohnzimmer
- badges: []
  cards:
  - entities:
    - cover.rolllade_buero_level
    - sensor.rolllade_buero_energy
    - sensor.rolllade_buero_power
    - head: zwave.rolllade_buero
      items:
      - sensor.rolllade_buero_system
      - sensor.rolllade_buero_alarm_level
      - sensor.rolllade_buero_alarm_type
      - sensor.rolllade_buero_power_management
      - sensor.rolllade_buero_power_management_2
      type: custom:fold-entity-row
    show_header_toggle: false
    title: "B\xFCro Rolllade"
    type: entities
  - entity: climate.heizen_buero_heating
    modes:
      heat:
        icon: mdi:hand-right
        include: true
      'off':
        include: true
    sensors:
    - entity: sensor.buro_temperatur
    step_size: 0.5
    type: custom:simple-thermostat
  - entities:
    - entity: sensor.heizen_buero_alarm_level
    - entity: sensor.heizen_buero_alarm_type
    - entity: sensor.heizen_buero_power_management
    - entity: zwave.heizen_buero
    show_header_toggle: false
    title: Buero Heizung
    type: entities
  - entity: climate.heizen_buero2_heating
    modes:
      heat:
        icon: mdi:hand-right
        include: true
      'off':
        include: true
    sensors:
    - entity: sensor.buro_temperatur
    step_size: 0.5
    type: custom:simple-thermostat
  icon: mdi:paperclip
  path: g_buero
  title: "B\xFCro"
- badges: []
  cards:
  - card:
      show_header_toggle: false
      title: "Ger\xE4te an"
      type: entities
    filter:
      include:
      - domain: light
        state: 'on'
      - domain: switch
        state: 'on'
    show_empty: false
    type: custom:monster-card
  - entities:
    - sensor.sensor_buro_bme280_temperature
    type: custom:mini-graph-card
  - filter:
      include:
      - key: climate.heizen_ei.*
    heading_name: List
    heading_state: States
    title: Attributes Card
    type: custom:entity-attributes-card
  - entities:
    - entity: sensor.licht_aquarium_bme280_pressure
    type: entities
  title: tt
- badges: []
  cards:
  - cards:
    - entity: climate.heizen_treppe_heat
      step_size: 0.5
      type: custom:simple-thermostat
    - entity: climate.heizen_treppe_heat_eco
      step_size: 0.5
      type: custom:simple-thermostat
    type: vertical-stack
  - cards:
    - entity: climate.heizen_eingang_heat
      step_size: 0.5
      type: custom:simple-thermostat
    - entity: climate.heizen_eingang_heat_eco
      step_size: 0.5
      type: custom:simple-thermostat
    type: vertical-stack
  - cards:
    - entity: climate.heizen_fenster_heat
      step_size: 0.5
      type: custom:simple-thermostat
    - entity: climate.heizen_fenster_heat_eco
      step_size: 0.5
      type: custom:simple-thermostat
    type: vertical-stack
  - cards:
    - entity: climate.wohnzimmer_heizung_sofa_heat
      step_size: 0.5
      type: custom:simple-thermostat
    - entity: climate.wohnzimmer_heizung_sofa_heat_eco
      step_size: 0.5
      type: custom:simple-thermostat
    type: vertical-stack
  - entity: climate.heizen_buero_heating
    step_size: 0.5
    type: custom:simple-thermostat
  - entity: climate.heizen_kueche_heating
    step_size: 0.5
    type: custom:simple-thermostat
  - entity: climate.heizen_flur_heating
    step_size: 0.5
    type: custom:simple-thermostat
  title: Heizung
- badges: []
  cards:
  - card:
      show_header_toggle: false
      title: Temperatur an
      type: entities
    filter:
      include:
      - entity_id: sensor.*Temperat*
    show_empty: false
    type: custom:monster-card
  - entities:
    - sensor.speicher_temperatur
    hours_to_show: 240
    points_per_hour: 0.25
    show:
      extrema: true
      labels: true
    type: custom:mini-graph-card
  - entities:
    - sensor.wohnzimmer_temperatur
    hours_to_show: 240
    points_per_hour: 0.25
    show:
      extrema: true
      labels: true
    type: custom:mini-graph-card
  - entities:
    - sensor.buro_temperatur
    hours_to_show: 240
    points_per_hour: 0.25
    show:
      extrema: true
      labels: true
    type: custom:mini-graph-card
  title: Temp
