binary_sensor:
  - platform: template
    sensors:
      bs_sun_up:
        friendly_name: "es ist hell"
        value_template: >-
          {{ states.sun.sun.attributes.elevation|float > 0 }}


sensor:
  - platform: mqtt
    state_topic: "tele/lled/STATE"
    name: Licht LED Wlan
    unit_of_measurement: "%"
    value_template:  "{{value_json['Wifi'].RSSI}}"
  - platform: mqtt
    state_topic: "tele/lled/STATE"
    name: Licht LED SSId
    value_template:  "{{value_json['Wifi'].SSId}}"

  - platform: mqtt
    name: Licht LED V
    state_topic: "tele/lled/STATE"
    unit_of_measurement: "V"
    value_template:  "{{value_json.Vcc}}"

  - platform: mqtt
    name: Licht LED LZ
    state_topic: "tele/lled/STATE"
    unit_of_measurement: "h"
    value_template:  "{{value_json.Uptime}}"
    
  - platform: mqtt
    name: Licht LED Version
    state_topic: "tele/lled/STATUS2"
    value_template:  "{{value_json['StatusFWR'].Version}}"

  - platform: mqtt
    name:  aussen Temperatur
    state_topic: "tele/rf434/tcm/245"
    unit_of_measurement: "°C"
    value_template:  "{{(value_json.temperature| float )| round(1)}}"  
 
  - platform: mqtt
    name:  aussen Feuchte
    state_topic: "tele/rf434/tcm/245"
    unit_of_measurement: "%"
    value_template:  "{{(value_json.humidity| float + 36)| round(1)}}"   

history_graph:
  gr28:
    name: Aussen Graph
    entities:
     - sensor.aussen_temperatur
     - sensor.aussen_feuchte
    hours_to_show: 240
    refresh: 150    

light:
  - platform: mqtt
    name: Licht LED
    state_topic: "tele/lled/POWER"
    command_topic: "cmnd/lled/POWER"
    availability_topic: "tele/lled/LWT"
    qos: 1
    optimistic: false
    retain: true

group:
  g_aussen_tracker:    
    name: Aussen Tracker
    entities:
    - device_tracker.lled

  g_aussen_sensor: 
    name: Sensor Aussen 
    view: no
    entities:
     - sensor.aussen_temperatur
     - sensor.aussen_feuchte

  g_led_schalter:
    name: Gruppe LED 
    view: no
    entities:
    - weblink.licht_led_web
    - light.licht_led
    - sensor.licht_led_wlan
    - sensor.licht_led_v
    - sensor.licht_led_lz
  g_aussen:
    view: yes
    name: Aussen
    icon: mdi:nature
    entities:
    - group.g_aussen_tracker
    - group.g_aussen_sensor
    - group.g_led_schalter
    - history_graph.aussen_graph
        
automation:
  - alias: LED Licht aus
    trigger:
      platform: sun
      event: sunrise
    action:
      - service: notify.wolfhome
        data:
          title: '*LED*'
          message: 'The sun is up.' 
      - service: light.turn_off
        entity_id: light.licht_led
      
  - alias: LED Licht an
    trigger:
      platform: sun
      event: sunset
    action:
      - service: notify.wolfhome
        data:
          title: '*LED*'
          message: 'The sun is down.' 
      - service: light.turn_on
        entity_id: light.licht_led
