
sensor:
    

  - platform: min_max
    name: Luminance
    type: min
    entity_ids:
      - sensor.eingang_strahler_luminance
      - sensor.hinten_strahler_luminance
      - sensor.vorne_strahler_luminance
 