

sensor:    
   
  - platform: template
    sensors:
      buro_soll:
        friendly_name: "Büro Sollwert"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('climate.heizung_buero_heating', 'temperature') }}"
       

