homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'Ha Server Monitor'
    sensor.average_load_15m:
      friendly_name: Cpu load_15m
      icon: mdi:speedometer
    sensor.ha_cpu_temperature:
      friendly_name: Ha Cpu Temperature
      icon: mdi:oil-temperature
    script.ha_dash_usage:
      friendly_name: HA Svr Notify Issue
      icon: mdi:chip
      haaska_hidden: true
    automation.ha_ram_overload:
      friendly_name: HA Svr Automation for Ram
    automation.ha_disk_overload:
      friendly_name: HA Svr Automation for Disk Space
    automation.ha_cpu_overload:
      friendly_name: HA Svr Automation for Cpu Load
    sensor.last_boot:
      friendly_name: Letzer Neustart
    sensor.processor_use:
      friendly_name: CPU Auslastung
    sensor.memory_free:
      friendly_name: Freier RAM
    sensor.network_in_eth0:
      friendly_name: Empfangen
    sensor.network_out_eth0:
      friendly_name: Gesendet
    sensor.disk_used_home:
      friendly_name: Genutzter Speicher Flash
#Speedtest
    sensor.speedtest_ping:
      icon: mdi:speedometer
      friendly_name: Ping
    sensor.speedtest_download:
      icon: mdi:download
      friendly_name: Download
    sensor.speedtest_upload:
      icon: mdi:upload
      friendly_name: Upload

group:
  linux_server_card:
   name: Ha Server
   entities:
     - sensor.speedtest_download
     - sensor.speedtest_upload
     - sensor.speedtest_ping
     - sensor.processor_use
     - sensor.load_15m
     - sensor.ha_cpu_temperature
     - sensor.disk_free_home
     - sensor.disk_use_percent_home
     - sensor.disk_used_home
     - sensor.memory_free
     - sensor.memory_use
     - sensor.memory_use_percent
     - sensor.swap_free
     - sensor.swap_use
     - sensor.swap_use_percent
     - sensor.network_in_eth0
     - sensor.network_out_eth0
     - sensor.packets_in_eth0
     - sensor.packets_out_eth0
     - ssensor.ipv4_address_eth0
     - sensor.last_boot
     - sensor.since_last_boot

  ha_server_automations:
   control: hidden
   name: HA Server Alerts
   entities:
    - input_number.ram_alert_value
    - input_number.disk_alert_value
    - input_number.cpu_alert_value
    - automation.ha_ram_overload
    - automation.ha_disk_overload
    - automation.ha_cpu_overload

sensor:
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: disk_use_percent
        arg: /home
      - type: disk_use
        arg: /home
      - type: disk_free
        arg: /home
      - type: memory_free
      - type: memory_use_percent
      - type: memory_use
      - type: swap_use_percent
      - type: swap_use
      - type: swap_free
      - type: load_15m
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: packets_in
        arg: eth0
      - type: packets_out
        arg: eth0
      - type: ipv4_address
        arg: eth0
      - type: last_boot
      - type: since_last_boot


#  - platform: command_line
#    name: Ha Cpu Temperature
#    command: cat /sys/class/thermal/thermal_zone0/temp
#    unit_of_measurement: '°C'
#    value_template: '{{ (value|int / 1000 )|round(1) }}'

  - platform: speedtest
    hour:
      - 8
      - 12
      - 16
      - 20
      - 22
    monitored_conditions:
      - ping
      - download
      - upload

input_number:
  ram_alert_value:
    name: HA Ram Alert Setpoint
    initial: 85
    min: 0
    max: 100
    step: 5
  disk_alert_value:
    name: HA Disk Alert Setpoint
    initial: 75
    min: 0
    max: 100
    step: 5
  cpu_alert_value:
    name: HA CPU Alert Setpoint
    initial: 80
    min: 0
    max: 100
    step: 5

history_graph:
  gr2:
    name: Speedtest
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
    hours_to_show: 48
    refresh: 120


automation:
############# Ram usuage high on BI server #####################################
  - alias: ha_ram_overload
    trigger:
      - platform: template
        value_template: "{{ states('sensor.ram_used_2') > states('input_number.ram_alert_value') }}"
    action:
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker
          message: 'Ram Usage On HA Server is Excessive'
      - service: notify.wolfhome
        data:
          title: '* HA Server*'
          message: 'Ram Usage Is Excessive On HA Server'
      - service: notify.chrome_push
        data_template:
          title: "HA Server"
          message: "Ram Usage On HA Server - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
          data:
            url: "/home_assistant_group.serversview"
      - service: persistent_notification.create
        data_template:
          title: "HA Server Ram Alert"
          message: "Check HA Server Ram Usage - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
          notification_id: "Ram On HA Server"

############# Disk usuage high on BI server #####################################
  - alias: ha_disk_overload
    trigger:
      - platform: template
        value_template: "{{ states('sensor.disk_used_home') > states('input_number.disk_alert_value') }}"
    action:
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker
          message: 'Disk Usage On HA Server is Excessive'
      - service: notify.wolfhome
        data:
          title: '* HA Server*'
          message: 'Disk Usage Is Excessive On HA Server'
      - service: notify.chrome_push
        data_template:
          title: "HA Server"
          message: "Disk Usage On HA Server - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
          data:
            url: "/home_assistant_group.serversview"
      - service: persistent_notification.create
        data_template:
          title: "HA Server Disk Alert"
          message: "Check HA Server Disk Usage - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
          notification_id: "Disk On HA Server"

####################### High Cpu Usage #########################################
  - alias: ha_cpu_overload
    trigger:
      - platform: template
        value_template: "{{ states('sensor.cpu_used')|int > states('input_number.cpu_alert_value')| int }}"
#        for: '00:00:30'
    action:
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker
          message: 'Cpu Usage On HA Server is Excessive'
      - service: notify.wolfhome
        data:
          title: '* HA Server*'
          message: 'Disk Usage Is Excessive On HA Server'
      - service: notify.chrome_push
        data_template:
          title: "HA Server"
          message: "CPU Usage On HA Server - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
          data:
            url: "/home_assistant_group.serversview"
      - service: persistent_notification.create
        data_template:
          title: "HA Server CPU Alert"
          message: "Check HA Server CPU Usage - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
          notification_id: "CPU On HA Server"
