homeassistant:
  customize:

    sensor.wolfgangda2_cpu_usage:
      friendly_name: DA 2 CPU Auslastung


switch:
  - platform: wake_on_lan
    name: Nas3 Wake
    mac_address: "00:11:32:83:E3:3E"
    host: "10.10.0.4"

  - platform: wake_on_lan
    name: Wolfgang da2 Wake
    mac_address: "00:08:9B:D1:73:18"
    host: "10.10.0.3"


  - platform: mqtt
    name: Radio Schalter Keller
    state_topic: "stat/r_schalter1/POWER"
    command_topic: "cmnd/r_schalter1/POWER"
    availability_topic: "tele/r_schalter1/LWT"
    qos: 1
    optimistic: false
    retain: false

binary_sensor:


#NAS


  - platform: mqtt
    name: Licht Keller Flur Taste
    state_topic: "cmnd/LKellerFlurex/POWER1"

  - platform: mqtt
    name: "Fenster Contact Keller L"
    state_topic: 'home/OpenFensterKellerL'
    payload_on: 'on'
    payload_off: 'off'
    device_class: window

  - platform: mqtt
    name: "Fenster Contact Keller R"
    state_topic: 'home/OpenFensterKellerR'
    payload_on: 'on'
    payload_off: 'off'
    device_class: window

sensor:
  - platform: mqtt
    name: Licht Keller Flur Wlan
    state_topic: "tele/LKellerFlur/STATE"
    unit_of_measurement: "%"
    value_template:  "{{value_json['Wifi'].RSSI}}"
  - platform: mqtt
    state_topic: "tele/LKellerFlur/STATE"
    name: Licht Keller Flur SSId
    value_template:  "{{value_json['Wifi'].SSId}}"

  - platform: mqtt
    name: Licht Keller Flur V
    state_topic: "tele/LKellerFlur/STATE"
    unit_of_measurement: "V"
    value_template:  "{{value_json.Vcc}}"

  - platform: mqtt
    name: Licht Keller Flur LZ
    state_topic: "tele/LKellerFlur/STATE"
    value_template:  "{{value_json.Uptime}}"

  - platform: mqtt
    name: Licht Keller Flur Version
    state_topic: "tele/LKellerFlur/STATUS2"
    value_template:  "{{value_json['StatusFWR'].Version}}"
    
  - platform: mqtt
    name: Licht Keller Flur Temperatur
    state_topic: "tele/LKellerFlur/STATUS10"
    unit_of_measurement: "°C"
    value_template:  "{{(value_json.StatusSNS.HTU21.Temperature| float + 0.1)| round(1)}}"

  - platform: mqtt
    name: Licht Keller Flur Feuchte
    state_topic: "tele/LKellerFlur/STATUS10"
    unit_of_measurement: "%"
    value_template:  "{{(value_json.StatusSNS.HTU21.Humidity| float + 2.9)| round(1)}}"

#qnap

  - platform: qnap
    state_topic: "home/technik"
    name: Wolfgang da2 Status
    host: 10.10.0.3
    username: !secret fritz_user
    password: !secret normal_password
    timeout: 30
    monitored_conditions:
      - status
      - cpu_usage
      - memory_percent_used
      - network_tx
      - network_rx
      - volume_percentage_used
      - drive_smart_status

  - platform: synologydsm
    host: 10.10.0.4
    port: 5000
    ssl: false
    username: status
    password: !secret normal_password
    monitored_conditions:
      - network_up
      - network_down
      - cpu_total_load
      - memory_real_usage
      - disk_status
      - disk_smart_status
      - disk_temp
      - volume_percentage_used
      - volume_disk_temp_avg
      - volume_disk_temp_max

  - platform: mqtt
    name: Radio Schalter Keller Wlan
    state_topic: "tele/r_schalter1/STATE"
    unit_of_measurement: "%"
    value_template:  "{{value_json['Wifi'].RSSI}}"
  - platform: mqtt
    state_topic: "tele/r_schalter1/STATE"
    name: Radio Schalter Keller SSId
    value_template:  "{{value_json['Wifi'].SSId}}"

  - platform: mqtt
    name: Radio Schalter Keller V
    state_topic: "tele/r_schalter1/STATE"
    unit_of_measurement: "V"
    value_template:  "{{value_json.Vcc}}"

  - platform: mqtt
    name: Radio Schalter Keller LZ
    state_topic: "tele/r_schalter1/STATE"
    value_template:  "{{value_json.Uptime}}"

  - platform: mqtt
    name: Radio Schalter Keller Version
    state_topic: "tele/r_schalter1/STATUS2"
    value_template:  "{{value_json['StatusFWR'].Version}}"
    
  - platform: mqtt
    name: Keller Temperatur
    state_topic: "tele/r_schalter1/STATUS10"
    unit_of_measurement: "°C"
    value_template:  "{{(value_json.StatusSNS.HTU21.Temperature| float + 0.9)| round(1)}}"

  - platform: mqtt
    name: Keller Feuchte
    state_topic: "tele/r_schalter1/STATUS10"
    unit_of_measurement: "%"
    value_template:  "{{(value_json.StatusSNS.HTU21.Humidity| float + 2.2)| round(1)}}"

history_graph:
  gr10:
    name: Keller Graph
    entities:
     - sensor.keller_temperatur
     - sensor.keller_feuchte
     - sensor.licht_keller_flur_temperatur
     - sensor.licht_keller_flur_feuchte
    hours_to_show: 240
    refresh: 60

light:
  - platform: mqtt
    name: Licht Keller Flur
    state_topic: "tele/LKellerFlur/POWER"
    command_topic: "cmnd/LKellerFlur/POWER"
    availability_topic: "tele/LKellerFlur/LWT"
    qos: 1
    optimistic: false
    retain: false

input_number:

  in_licht_keller_flur:
    name: Licht Keller Flur Zeit
    mode: slider
    min: 10
    max: 40
    step: 1

automation:

  - alias: Licht Keller Flur An
    trigger:
      - platform: state
        entity_id: binary_sensor.licht_keller_flur_taste
        to: "on"
    action:
      - service: light.turn_on
        entity_id: light.licht_keller_flur

  - alias: Licht Keller Flur Timer Start
    trigger:
      platform: state
      entity_id: binary_sensor.licht_keller_flur_taste
      from: 'on'
      to: 'off'
    action:
      service: script.turn_on
      entity_id: script.licht_keller_flur_motion

  - alias: Licht Keller Flur Timer Cancel
    trigger:
      platform: state
      entity_id: binary_sensor.licht_keller_flur_taste
      from: 'off'
      to: 'on'
    action:
      service: script.turn_off
      entity_id: script.licht_keller_flur_motion  

  - alias: "Keller Radio an started from Harmony Hub"
    trigger:
      platform: state
      entity_id: remote.wohnzimmer
    condition:
      condition: template
      value_template: '{{ trigger.to_state.attributes.current_activity == "RSH Keller An" }}'
    action:
      - service: input_select.select_option
        entity_id: input_select.remote
        data:
          option: "RSH Keller An"
      - service: switch.turn_on
        entity_id: switch.radio_schalter_keller
      - service: switch.turn_on
        entity_id: switch.sw_mpd_hrs
      - service: notify.wolfhome
        data:
         title: '*Radio Keller*'
         message: ' an Schalter' 
  - alias: Keller Radio An FB
    trigger:
      platform: state
      entity_id: binary_sensor.gt9000_197432_3
      from: 'off'
      to: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.radio_schalter_keller

  - alias: "Keller Radio aus started from Harmony Hub"
    trigger:
      platform: state
      entity_id: remote.wohnzimmer
    condition:
      condition: template
      value_template: '{{ trigger.to_state.attributes.current_activity == "RSH Keller aus" }}'
    action:
      - service: input_select.select_option
        entity_id: input_select.remote
        data:
          option: "RSH Keller aus"
      - service: switch.turn_off
        entity_id: switch.radio_schalter_keller
      - service: notify.wolfhome
        data:
         title: '*Radio Keller*'
         message: ' aus Schalter' 

  - alias: Keller Radio Aus FB
    trigger:
      platform: state
      entity_id: binary_sensor.gt9000_197432_3
      from: 'on'
      to: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.radio_schalter_keller

script:
  licht_keller_flur_motion:
    sequence:
      - delay: >-
          {% set duration = states.input_number.in_licht_keller_flur.state | int %}
          {% if duration > 0 %}
            {% set duration = duration - 1 %}
          {% endif %}
          {% set seconds = duration % 60 %}
          {% set minutes = (duration / 60)|int % 60 %}
          {% set hours = (duration / 3600)|int %}
          {{ [hours, minutes, seconds]|join(':') }}
      - service: light.turn_off
        data_template:
          entity_id: light.licht_keller_flur


group:
  g_nas3:
    name: Nas 3
    entities:
    - weblink.nas3_web
    - switch.nas3_wake
    - sensor.network_down
    - sensor.network_up
    - sensor.temperature_sda
    - sensor.maximum_disk_temp_volume_1
    - sensor.volume_used_volume_1
    - sensor.temperature_sdb
    - sensor.maximum_disk_temp_volume_2
    - sensor.volume_used_volume_2
    - sensor.status_sda
    - sensor.status_sdb
    - sensor.status_smart_sda
    - sensor.status_smart_sdb

  g_wolfgang_da2:
    name: Nas 2
    entities:
    - weblink.wolfgang_da2_web
    - switch.wolfgang_da2_wake
    - sensor.wolfgangda2_cpu_usage
    - sensor.wolfgangda2_memory_usage
    - sensor.wolfgangda2_network_up_eth0
    - sensor.wolfgangda2_network_down_eth0
    - sensor.wolfgangda2_status
    - sensor.wolfgangda2_volume_used_volume_1
    - sensor.wolfgangda2_smart_status_drive_1
    - sensor.wolfgangda2_volume_used_volume_2
    - sensor.wolfgangda2_smart_status_drive_2

  g_licht_keller_flur:
    name: Licht Keller Flur
    entities:
    - weblink.licht_keller_flur_web
    - light.licht_keller_flur
    - input_number.in_licht_keller_flur
    - sensor.licht_keller_flur_wlan
    - sensor.licht_keller_flur_v
    - sensor.licht_keller_flur_lz
    - binary_sensor.licht_keller_flur_taste

  g_keller_tracker:    
    name: Keller Tracker
    entities:
    - device_tracker.dm500plus
    - device_tracker.piradio2fritzbox
    - device_tracker.rschalter1fritzbox
    - device_tracker.lkellerflur
    - device_tracker.wlankeller
    - device_tracker.nas3
    - device_tracker.wolfgangda2

  g_radio_schalter_keller:
    name: Gruppe Radio Schalter Keller 
    view: no
    entities:
    - weblink.radio_schalter_keller_web
    - switch.radio_schalter_keller
    - sensor.radio_schalter_keller_wlan
    - sensor.radio_schalter_keller_v
    - sensor.radio_schalter_keller_lz



  g_keller_sensor:
    name: Keller Sensor
    view: no
    entities:
    - sensor.keller_temperatur
    - sensor.keller_feuchte
    - sensor.licht_keller_flur_temperatur
    - sensor.licht_keller_flur_feuchte
    - binary_sensor.fenster_contact_keller_l
    - binary_sensor.fenster_contact_keller_r
    - binary_sensor.fenster_contact_keller_l_alarm
    - binary_sensor.fenster_contact_keller_r_alarm

  g_keller:
    view: yes
    name: Keller
    icon: mdi:stairs
    entities:
    - group.g_keller_tracker
    - group.g_keller_sensor
    - group.g_licht_keller_flur
    - history_graph.keller_graph
    - group.g_nas3
    - group.g_wolfgang_da2
    - group.g_radio_schalter_keller
    - media_player.snapcast_client_26b35c57806c4797b27cd6e878effeb5_2

