#homeassistant:
#  customize:
  



binary_sensor:

  - platform: mqtt
    name: Radio Schalter Kueche Taste
    state_topic: "cmnd/r_schalterex/POWER1"

  - platform: mqtt
    name: "Kuechentuer Kontakt"
    state_topic: 'home/OpenDoorKueche'
    payload_on: 'on'
    payload_off: 'off'
    device_class: door

  - platform: mqtt
    name: "Kuechenfenster Kontakt"
    state_topic: 'home/OpenFensterKueche'
    payload_on: 'on'
    payload_off: 'off'
    device_class: window
   
    
sensor:
  - platform: mqtt
    state_topic: "tele/r_schalter/STATE"
    name: Radio Schalter Kueche Wlan
    unit_of_measurement: "%"
    value_template:  "{{value_json['Wifi'].RSSI}}"
  - platform: mqtt
    state_topic: "tele/r_schalter/STATE"
    name: Radio Schalter Kueche SSId
    value_template:  "{{value_json['Wifi'].SSId}}"

  - platform: mqtt
    name: Radio Schalter Kueche V
    state_topic: "tele/r_schalter/STATE"
    unit_of_measurement: "V"
    value_template:  "{{value_json.Vcc}}"

  - platform: mqtt
    name: Radio Schalter Kueche LZ
    state_topic: "tele/r_schalter/STATE"
    value_template:  "{{value_json.Uptime}}"

  - platform: mqtt
    name: Radio Schalter Kueche Version
    state_topic: "tele/r_schalter/STATUS2"
    value_template:  "{{value_json['StatusFWR'].Version}}"
    
  - platform: mqtt
    name: Kueche Temperatur
    state_topic: "tele/r_schalter/STATUS10"
    unit_of_measurement: "°C"
    value_template:  "{{(value_json.StatusSNS.HTU21.Temperature| float - 3.0)| round(1)}}"

  - platform: mqtt
    name: Kueche Feuchte
    state_topic: "tele/r_schalter/STATUS10"
    unit_of_measurement: "%"
    value_template:  "{{(value_json.StatusSNS.HTU21.Humidity| float + 13.0)| round(1)}}"

# POW
  - platform: mqtt
    state_topic: "tele/pkaffee/STATE"
    name: Pow Kaffee Wlan
    unit_of_measurement: "%"
    value_template:  "{{value_json['Wifi'].RSSI}}"
  - platform: mqtt
    state_topic: "tele/pkaffee/STATE"
    name: Pow Kaffee SSId
    value_template:  "{{value_json['Wifi'].SSId}}"

  - platform: mqtt
    name: Pow Kaffee V
    state_topic: "tele/pkaffee/STATE"
    unit_of_measurement: "V"
    value_template:  "{{value_json.Vcc}}"

  - platform: mqtt
    name: Pow Kaffee LZ
    state_topic: "tele/pkaffee/STATE"
    value_template:  "{{value_json.Uptime}}"
    
  - platform: mqtt
    name: Pow Kaffee Version
    state_topic: "tele/pkaffee/STATUS2"
    value_template:  "{{value_json['StatusFWR'].Version}}"
  - platform: mqtt
    name: "Pow Garage Today"
    state_topic: "tele/pgarage/STATUS10"
    value_template: '{{ value_json.StatusSNS.ENERGY.Today }}'
    
  - platform: mqtt
    name: "Pow Kaffee Today"
    state_topic: "tele/pkaffee/STATUS10"
    value_template: '{{ value_json.StatusSNS.ENERGY.Today }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Pow Kaffee Power"
    state_topic: "tele/pkaffee/STATUS10"
    value_template: '{{ value_json.StatusSNS.ENERGY.Power }}'
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Pow Kaffee Voltage"
    state_topic: "tele/pkaffee/STATUS10"
    value_template: '{{ value_json.StatusSNS.ENERGY.Voltage }}'
    unit_of_measurement: "V"
  - platform: mqtt
    name: "Pow Kaffee Current"
    state_topic: "tele/pkaffee/STATUS10"
    value_template: '{{ value_json.StatusSNS.ENERGY.Current }}'
    unit_of_measurement: "A"
    
  - platform: mqtt
    name: "Pow Kaffee Yesterday"
    state_topic: "tele/pkaffee/STATUS10"
    value_template: '{{ value_json.StatusSNS.ENERGY.Yesterday }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Pow Kaffee Total"
    state_topic: "tele/pkaffee/STATUS10"
    value_template: '{{ value_json.StatusSNS.ENERGY.Total }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Pow Kaffee Factor"
    state_topic: "tele/pkaffee/STATUS10"
    value_template: '{{ value_json.StatusSNS.ENERGY.Factor }}'


history_graph:

  gr22:
    name: Küche Graph
    entities:
     - sensor.kueche_temperatur
     - sensor.kueche_feuchte
     - sensor.pow_kaffee_voltage
     - sensor.pow_kaffee_current
    hours_to_show: 240
    refresh: 60

switch:
  - platform: mqtt
    name: Radio Schalter Kueche
    state_topic: "stat/r_schalter/POWER"
    command_topic: "cmnd/r_schalter/POWER"
    availability_topic: "tele/r_schalter/LWT"
    qos: 1
    optimistic: false
    retain: true

  - platform: mqtt
    name: Pow Kaffee
    state_topic: "tele/pkaffee/POWER"
    command_topic: "cmnd/pkaffee/POWER"
    availability_topic: "tele/pkaffee/LWT"
    qos: 1
    optimistic: false
    retain: true

media_player:

  - platform: kodi
    name: Kueche Kodi
    host: amazon-cdea109b9.fritz.box

  - platform: universal
    name: Test Universal
    children:
      - media_player.pi_media_mpd
      - media_player.snapcast_client_6aec95f148e44614adcf25c2fafed2c0_2
    commands:
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.living_room_tv
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.living_room_tv
      volume_up:
        service: switch.turn_on
        data:
          entity_id: switch.living_room_volume_up
      volume_down:
        service: switch.turn_on
        data:
          entity_id: switch.living_room_volume_down
      volume_mute:
        service: switch.turn_on
        data:
          entity_id: switch.living_room_mute

          
input_number:

  in_mpd_kueche:
    name: Küchelautstärke
    mode: slider
    min: 0
    max: 1
    step: 0.05


automation:

  - alias: Radio An Werktags
    trigger:
      platform: time
      at: 06:00:00
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.bs_workday
          state: 'on'
        - condition: state
          entity_id: input_boolean.boolean_urlaub
          state: 'off'
    action:
      - service: switch.turn_on
        entity_id: switch.sw_mpd_hrs
      - service: media_player.volume_set
        # Note the use of 'data_template:' below rather than the normal 'data:' if you weren't using an input variable
        data_template:
          entity_id: media_player.pi_media_mpd
          volume_level: 1.0
      - service: switch.turn_on
        entity_id: switch.radio_schalter_kueche
      - service: notify.wolfhome
        data:
         title: '*Radio*'
         message: ' an Werktags' 

  - alias: Radio An MPD
    trigger:
      platform: state
      entity_id: media_player.pi_media_mpd
      to: 'playing'
    action:
     - service: switch.turn_on
       entity_id: switch.radio_schalter_kueche

  - alias: 'pi-radio ausschalten'
    trigger:
      platform: state
      entity_id: media_player.pi_media_mpd
      to: 'off'
    action:
     - service: switch.turn_off
       entity_id: switch.radio_schalter_kueche

  - alias: Radio An Schalter
    trigger:
      platform: state
      entity_id: binary_sensor.radio_schalter_kueche_taste
      to: 'on'
      for:
        seconds: 1
    condition:
      condition: state
      entity_id: binary_sensor.bs_play_mpd
      state: 'off'
    action:
      - service: switch.turn_on
        entity_id: switch.sw_mpd_hrs
      - service: switch.turn_on
        entity_id: switch.radio_schalter_kueche
      - service: notify.wolfhome
        data:
         title: '*Radio*'
         message: ' an Schalter' 
      - service: remote.turn_on
        entity_id: remote.wohnzimmer
        data:
          activity: 31664117
            
  - alias: Radio Aus Schalter
    trigger:
      platform: state
      entity_id: binary_sensor.radio_schalter_kueche_taste
      to: 'on'
      for:
        seconds: 1
    condition:
        - condition: state
          entity_id: binary_sensor.bs_play_mpd
          state: 'on'
    action:
      - service: media_player.turn_off
        # Note the use of 'data_template:' below rather than the normal 'data:' if you weren't using an input variable
        data_template:
          entity_id: media_player.pi_media_mpd
      - service: switch.turn_off
        entity_id: switch.radio_schalter_kueche
      - service: switch.turn_off
        entity_id: switch.radio_schalter_keller
      - service: notify.wolfhome
        data:
         title: '*Radio*'
         message: ' aus Schalter' 
      - service: remote.turn_off
        entity_id: remote.wohnzimmer


  - alias: Lautstaerke - Kueche
    trigger:
      platform: state
      entity_id: input_number.in_mpd_kueche
    condition:
      condition: state
      entity_id: media_player.pi_media_mpd
      state: 'playing'
    action:
      - service: media_player.volume_set
        # Note the use of 'data_template:' below rather than the normal 'data:' if you weren't using an input variable
        data_template:
          entity_id: media_player.snapcast_client_6aec95f148e44614adcf25c2fafed2c0_2
          volume_level: '{{ trigger.to_state.state }}'
      - service: notify.wolfhome
        data:
          title: '*Radio*'
          message: 'Küchenlautstärke {{ trigger.to_state.state }}' 

  - alias: Kaffee an Werktags
    trigger:
      platform: time
      at: '5:30'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.bs_workday
          state: 'on'
        - condition: state
          entity_id: input_boolean.boolean_urlaub
          state: 'off'
    action:
      - service: switch.turn_on
        entity_id: switch.pow_kaffee

  - alias: Kaffee an
    trigger:
      platform: time
      at: '6:45'
    action:
      - service: switch.turn_on
        entity_id: switch.pow_kaffee
        

  - alias: Kaffee aus
    trigger:
      platform: time
      at: '23:30'
    action:
      - service: switch.turn_off
        entity_id: switch.pow_kaffee

         
group:
  g_kueche_tracker:
    view: no
    name: Tracker Küche
    entities:
    - device_tracker.thermomix30c10e
    - device_tracker.amazoncdea109b9
    - device_tracker.piradio
    - device_tracker.rschalter
    - device_tracker.galaxytaba2016
    - device_tracker.wlankueche
    
  g_kaffee_pow:
    name: Kaffee POW 
    view: no
    entities:
    - weblink.pow_kaffee_web
    - switch.pow_kaffee
    - sensor.pow_kaffee_wlan
    - sensor.pow_kaffee_v
    - sensor.pow_kaffee_lz
    - sensor.pow_kaffee_voltage
    - sensor.pow_kaffee_current
    - sensor.pow_kaffee_factor
    - sensor.pow_kaffee_power
    - sensor.pow_kaffee_today
    - sensor.pow_kaffee_yesterday
    - sensor.pow_kaffee_total


  g_pi_k_schalter:
    name: Gruppe Radio Schalter Küche 
    view: no
    entities:
    - weblink.radio_schalter_kueche_web
    - switch.radio_schalter_kueche
    - sensor.radio_schalter_kueche_wlan
    - sensor.radio_schalter_kueche_v
    - sensor.radio_schalter_kueche_lz
    - binary_sensor.radio_schalter_kueche_taste


  g_kueche_sensor:
    name: Sensor Küche 
    view: no
    entities:
    - sensor.kueche_temperatur
    - sensor.kueche_feuchte
    - binary_sensor.kuechenfenster_kontakt
    - binary_sensor.kuechenfenster_kontakt_batt
    - binary_sensor.kuechentuer_kontakt
    - binary_sensor.kuechentuer_kontakt_batt
  

  g_kueche:
    view: yes
    name: kueche
    icon: mdi:food-fork-drink
    entities:
    - group.g_kueche_tracker
    - group.g_kueche_sensor
    - group.g_kaffee_pow
    - history_graph.kuche_graph
    - group.g_radio
    - group.g_pi_k_schalter
    - media_player.kueche_kodi
    - media_player.snapcast_client_6aec95f148e44614adcf25c2fafed2c0

