homeassistant:
  customize:
    zone.home:
      friendly_name: Wolfgangs und Barbaras Home

#Datum
    sensor.s_time_date:
      friendly_name: Datum/Zeit
   

sensor:
  - platform: moon
    name: Mond

 

