

binary_sensor:

  - platform: mqtt
    name: Licht Treppe Speicher Taste
    state_topic: "cmnd/LTreppeObenex/POWER1"


sensor:
  - platform: mqtt
    name: Licht Treppe Speicher Wlan
    state_topic: "tele/LTreppeOben/STATE"
    unit_of_measurement: "%"
    value_template:  "{{value_json['Wifi'].RSSI}}"
  - platform: mqtt
    state_topic: "tele/LTreppeOben/STATE"
    name: Licht Treppe Speicher SSId
    value_template:  "{{value_json['Wifi'].SSId}}"

  - platform: mqtt
    name: Licht Treppe Speicher V
    state_topic: "tele/LTreppeOben/STATE"
    unit_of_measurement: "V"
    value_template:  "{{value_json.Vcc}}"

  - platform: mqtt
    name: Licht Treppe Speicher LZ
    state_topic: "tele/LTreppeOben/STATE"
    value_template:  "{{value_json.Uptime}}"

  - platform: mqtt
    name: Licht Treppe Speicher Version
    state_topic: "tele/LTreppeOben/STATUS2"
    value_template:  "{{value_json['StatusFWR'].Version}}"

  - platform: mqtt
    name: Treppe Speicher Temperatur
    state_topic: "tele/LTreppeOben/STATUS10"
    unit_of_measurement: "°C"
    value_template:  "{{(value_json.StatusSNS.HTU21.Temperature| float - 0.1)| round(1)}}"

  - platform: mqtt
    name: Treppe Speicher Feuchte
    state_topic: "tele/LTreppeOben/STATUS10"
    unit_of_measurement: "%"
    value_template:  "{{(value_json.StatusSNS.HTU21.Humidity| float + 2.9)| round(1)}}"

# Fritzbox
  - platform: fritzbox_netmonitor
    state_topic: "technik/fritz"
    Host: fritz.box

  - platform: fritzbox_callmonitor
    state_topic: "technik/fritz"
    name: s_fritz_callmonitor
    host: 10.10.0.1
    username: !secret fritz_user2
    password: !secret fritz_user2_pw
    phonebook: 0
    prefixes:
      - !secret fritz_de
      - !secret fritz_dedo
      - !secret fritz_do

  - platform: template
    sensors:
      fritz_transmission_down_speed:
        friendly_name: "Aktuelle Datenrate down"
        unit_of_measurement: 'kbit/s'
        value_template: >-
          {% if states.sensor.fritz_netmonitor.attributes.transmission_rate_down|float > 0  %}
            {{ '{:.0f}'.format(states.sensor.fritz_netmonitor.attributes.transmission_rate_down|float/ 1024*8) }}
          {% else %}
            0
          {% endif %}  
      fritz_transmission_up_speed:
        friendly_name: "Aktuelle Datenrate up"
        unit_of_measurement: 'kbit/s'
        value_template: >- 
          {% if states.sensor.fritz_netmonitor.attributes.transmission_rate_up|float > 0  %}
            {{ '{:.0f}'.format(states.sensor.fritz_netmonitor.attributes.transmission_rate_up|float/ 1024*8) }}
          {% else %}
            0
          {% endif %}  
      fritz_max_down_speed:
        friendly_name: "Leitungskapazität down"
        unit_of_measurement: 'kbit/s'
        value_template: "{{ '{:.0f}'.format(states.sensor.fritz_netmonitor.attributes.max_byte_rate_down|float/ 1024*8) }}"  
      fritz_max_up_speed:
        friendly_name: "Leitungskapazität up"
        unit_of_measurement: 'kbit/s'
        value_template: "{{ '{:.0f}'.format(states.sensor.fritz_netmonitor.attributes.max_byte_rate_up|float/ 1024*8) }}" 
      fritz_received:
        friendly_name: "Empfangen"
        unit_of_measurement: 'kbit/s'
        value_template: "{{ '{:.0f}'.format(states.sensor.fritz_netmonitor.attributes.bytes_received|float/ 1024*8) }}"  
      fritz_send:
        friendly_name: "Gesendet"
        unit_of_measurement: 'kbit/s'
        value_template: "{{ '{:.0f}'.format(states.sensor.fritz_netmonitor.attributes.bytes_sent|float/ 1024*8) }}" 



light:
  - platform: mqtt
    name: Licht Treppe Speicher
    state_topic: "stat/LTreppeOben/POWER"
    command_topic: "cmnd/LTreppeOben/POWER"
    availability_topic: "tele/LTreppeOben/LWT"
    qos: 1
    optimistic: false
    retain: true

input_number:

  in_licht_treppe_speicher:
    name: Licht Treppe Speicher Zeit
    mode: slider
    min: 10
    max: 360
    step: 1

history_graph:
  gr30:
    name: Oben Graph
    entities:
    - sensor.treppe_speicher_temperatur
    - sensor.treppe_speicher_feuchte
    hours_to_show: 240
    refresh: 60
  grff:
    name: Internet
    entities:
      - sensor.fritz_transmission_down_speed
      - sensor.fritz_transmission_up_speed
    hours_to_show: 48
    refresh: 120
    
automation:

  - alias: Licht Treppe Oben An
    trigger:
      - platform: state
        entity_id: binary_sensor.licht_treppe_speicher_taste
        to: "on"
#        for:
#          seconds: 4
    action:
      - service: light.turn_on
        entity_id: light.licht_treppe_speicher


  - alias: Licht Treppe Oben Timer Start
    trigger:
      platform: state
      entity_id: binary_sensor.licht_treppe_speicher_taste
      from: 'on'
      to: 'off'
    action:
      service: script.turn_on
      entity_id: script.licht_treppe_speicher_motion

  - alias: Licht Treppe Oben Timer Cancel
    trigger:
      platform: state
      entity_id: binary_sensor.licht_treppe_speicher_taste
      from: 'off'
      to: 'on'
    action:
      service: script.turn_off
      entity_id: script.licht_treppe_speicher_motion  

script:
  licht_treppe_speicher_motion:
    sequence:
      - delay: >-
          {% set duration = states.input_number.in_licht_treppe_speicher.state | int %}
          {% if duration > 0 %}
            {% set duration = duration - 1 %}
          {% endif %}
          {% set seconds = duration % 60 %}
          {% set minutes = (duration / 60)|int % 60 %}
          {% set hours = (duration / 3600)|int %}
          {{ [hours, minutes, seconds]|join(':') }}
      - service: light.turn_off
        data_template:
          entity_id: light.licht_treppe_speicher
group:

  g_tracker_oben:    
    name: Tracker Oben
    view: no
    entities:
    - device_tracker.drucker
    - device_tracker.wlannetz
    - device_tracker.fritzbox

  g_fritz:
    name: FritzBox
    icon: mdi:access-point-network
    entities:
    - weblink.fritz_box
    - sensor.fritz_netmonitor
    - sensor.s_fritz_callmonitor
    - binary_sensor.bs_fritz_repeater
    - binary_sensor.bs_fritz_box_7390
    - history_graph.speedtest
    - history_graph.internet

  g_fritz_sensor:
    name: Daten Fritzbox
    entities:
    - sensor.fritz_transmission_down_speed
    - sensor.fritz_transmission_up_speed
    - sensor.fritz_max_down_speed
    - sensor.fritz_max_up_speed
    - sensor.fritz_received
    - sensor.fritz_send

  g_licht_treppe_oben:
    name: Licht Treppe Speicher
    entities:
    - weblink.licht_treppe_speicher_web
    - light.licht_treppe_speicher
    - input_number.in_licht_treppe_speicher
    - sensor.licht_treppe_speicher_wlan
    - sensor.licht_treppe_speicher_v
    - sensor.licht_treppe_speicher_lz
    - binary_sensor.licht_treppe_speicher_taste

  g_oben_sensor:
    name: Sensor Oben 
    view: no
    entities:
    - sensor.treppe_speicher_temperatur
    - sensor.treppe_speicher_feuchte

  g_oben:
    name: Oben
    icon: mdi:arrow-up-thick
    view: yes
    entities:
    - group.g_tracker_oben
    - group.g_oben_sensor
    - group.g_fritz
    - group.g_fritz_sensor
    - group.g_licht_treppe_oben
    - history_graph.oben_graph
#    - camera.buro


