sensor:
  - platform: mqtt
    name: "sonoff-workbench energy"
    state_topic: "tele/sonoff-workbench/ENERGY"
    value_template: "{{ value_json.Today }}"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "sonoff-workbench power"
    state_topic: "tele/sonoff-workbench/ENERGY"
    value_template: "{{ value_json.Power }}"
    unit_of_measurement: "W"
  - platform: mqtt
    name: "sonoff-workbench voltage"
    state_topic: "tele/sonoff-workbench/ENERGY"
    value_template: "{{ value_json.Voltage }}"
    unit_of_measurement: "V"

binary_sensor:
  - platform: mqtt
    name: "sonoff-workbench lwt"
    state_topic: "tele/sonoff-workbench/LWT"
    value_template: "{{ value }}"
    payload_on: "Online"
    payload_off: "Offline"
    device_class: connectivity

switch:
  - platform: mqtt
    name: "sonoff-workbench"
    state_topic: "stat/sonoff-workbench/POWER"
    command_topic: "cmnd/sonoff-workbench/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

