#homeassistant:
#  customize:
#    binary_sensor.zzztuer_contact_kueche:
#      hidden: true 
#    binary_sensor.zzzfenster_contact_kueche:
#      hidden: true 
#    binary_sensor.zzzfenster_contact_wohnzimmer:
#      hidden: true 
#    binary_sensor.zzzfenster_contact_treppe:
#      hidden: true 
#    binary_sensor.zzzfenster_contact_wc:
#      hidden: true 
#    binary_sensor.zzzfenster_contact_vorrat:
#      hidden: true 
#    binary_sensor.zzzfenster_contact_keller_r:
#      hidden: true 
#    binary_sensor.zzzfenster_contact_keller_l:
#      hidden: true 
      
sensor:
  - platform: mqtt
    state_topic: "tele/rfbridge/STATE"
    name: RF Bridge Wlan
    unit_of_measurement: "%"
    value_template:  "{{value_json['Wifi'].RSSI}}"
  - platform: mqtt
    state_topic: "tele/rfbridge/STATE"
    name: RF Bridge SSId
    value_template:  "{{value_json['Wifi'].SSId}}"

  - platform: mqtt
    name: RF Bridge V
    state_topic: "tele/rfbridge/STATE"
    unit_of_measurement: "V"
    value_template:  "{{value_json.Vcc}}"
  - platform: mqtt
    name: RF Bridge Version
    state_topic: "tele/rfbridge/STATUS2"
    value_template:  "{{value_json['StatusFWR'].Version}}"

  - platform: mqtt
    name: RF Bridge LZ
    state_topic: "tele/rfbridge/STATE"
    value_template:  "{{value_json.Uptime}}"
  - platform: mqtt
    name: RF Bridge Result
    state_topic: "tele/rfbridge/RFRECEIVED"
    value_template:  "{{value_json.RfReceived.Data}}"

binary_sensor:
  - platform: mqtt
    name: "RF Bridge lwt"
    state_topic: "tele/rfbridge/LWT"
    value_template: "{{ value }}"
    payload_on: "online"
    payload_off: "offline"
    device_class: connectivity


  - platform: mqtt
    name: "zzzFenster Contact Keller L"
    state_topic: "tele/rfbridge/RFRECEIVED"
    payload_on: "C1F6EE"
    payload_off: "C1F6E7"
    qos: 0
    device_class: opening
    value_template: '{{ value_json.RfReceived.Data }}'
    
  - platform: mqtt
    name: "Fenster Contact Keller L Alarm"
    state_topic: "tele/rfbridge/RFRECEIVED"
    payload_on: "C1F6EB"
    payload_off: "C1F6E7"
    qos: 0
    device_class: battery
    value_template: '{{ value_json.RfReceived.Data }}'

  - platform: mqtt
    name: "zzzFenster Contact Keller R"
    state_topic: "tele/rfbridge/RFRECEIVED"
    payload_on: "D2A5EE"
    payload_off: "D2A5E7"
    qos: 0
    device_class: opening
    value_template: '{{ value_json.RfReceived.Data }}'
    
  - platform: mqtt
    name: "Fenster Contact Keller R Alarm"
    state_topic: "tele/rfbridge/RFRECEIVED"
    payload_on: "D2A5EB"
    payload_off: "D2A5E7"
    qos: 0
    device_class: battery
    value_template: '{{ value_json.RfReceived.Data }}'
    
automation:
    

          

 #Keller          
  - alias: OpenFensterKellerRON
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.zzzfenster_contact_keller_r
        to: 'on'
    action:
      - service: mqtt.publish
        data:
          topic: "home/OpenFensterKellerR"
          payload: 'on'
          qos: 0
          retain: true
  - alias: OpenFensterKellerROff
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.zzzfenster_contact_keller_r
        to: 'off'
    action:
      - service: mqtt.publish
        data:
          topic: "home/OpenFensterKellerR"
          payload: 'off'
          qos: 0
          retain: true

  - alias: OpenFensterKellerLON
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.zzzfenster_contact_keller_l
        to: 'on'
    action:
      - service: mqtt.publish
        data:
          topic: "home/OpenFensterKellerL"
          payload: 'on'
          qos: 0
          retain: true
  - alias: OpenFensterKellerLOff
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.zzzfenster_contact_keller_l
        to: 'off'
    action:
      - service: mqtt.publish
        data:
          topic: "home/OpenFensterKellerL"
          payload: 'off'
          qos: 0
          retain: true
          
group:
  g_rf_bridge:
    name: Gruppe RF Bridge Buero 
    view: no
    entities:
    - weblink.rf_bridge_web
    - sensor.rf_bridge_wlan
    - sensor.rf_bridge_v
    - sensor.rf_bridge_lz
    - sensor.rf_bridge_version
    - sensor.rf_bridge_result
    - binary_sensor.rf_bridge_lwt
    - binary_sensor.node_red_lwt

  g_bridge:
    view: yes
    name: Rf Bridge
    icon: mdi:access-point
    entities:
    - group.g_rf_bridge
