     
sensor:
  - platform: mqtt
    state_topic: "tele/rfbridge/STATE"
    name: RF Bridge Wlan
    unit_of_measurement: "%"
    value_template:  "{{value_json['Wifi'].RSSI}}"
  - platform: mqtt
    state_topic: "tele/rfbridge/STATE"
    name: RF Bridge SSId
    value_template:  "{{value_json['Wifi'].SSId}}"

  - platform: mqtt
    name: RF Bridge V
    state_topic: "tele/rfbridge/STATE"
    unit_of_measurement: "V"
    value_template:  "{{value_json.Vcc}}"
  - platform: mqtt
    name: RF Bridge Version
    state_topic: "tele/rfbridge/STATUS2"
    value_template:  "{{value_json['StatusFWR'].Version}}"

  - platform: mqtt
    name: RF Bridge LZ
    state_topic: "tele/rfbridge/STATE"
    value_template:  "{{value_json.Uptime}}"
  - platform: mqtt
    name: RF Bridge Result
    state_topic: "tele/rfbridge/RFRECEIVED"
    value_template:  "{{value_json.RfReceived.Data}}"

binary_sensor:
  - platform: mqtt
    name: "RF Bridge lwt"
    state_topic: "tele/rfbridge/LWT"
    value_template: "{{ value }}"
    payload_on: "online"
    payload_off: "offline"
    device_class: connectivity


          
group:
  g_rf_bridge:
    name: Gruppe RF Bridge Buero 
    view: no
    entities:
    - weblink.rf_bridge_web
    - sensor.rf_bridge_wlan
    - sensor.rf_bridge_v
    - sensor.rf_bridge_lz
    - sensor.rf_bridge_version
    - sensor.rf_bridge_result
    - binary_sensor.rf_bridge_lwt
    - binary_sensor.node_red_lwt

  g_bridge:
    view: yes
    name: Rf Bridge
    icon: mdi:access-point
    entities:
    - group.g_rf_bridge
