sensor:
  - platform: mqtt
    name: Rollladen Schlafzimmer Wlan
    state_topic: "tele/dualschlaf/STATE"
    unit_of_measurement: "%"
    value_template:  "{{value_json['Wifi'].RSSI}}"
  - platform: mqtt
    state_topic: "tele/dualschlaf/STATE"
    name: Rollladen Schlafzimmer SSId
    value_template:  "{{value_json['Wifi'].SSId}}"

  - platform: mqtt
    name: Rollladen Schlafzimmer V
    state_topic: "tele/dualschlaf/STATE"
    unit_of_measurement: "V"
    value_template:  "{{value_json.Vcc}}"

  - platform: mqtt
    name: Rollladen Schlafzimmer LZ
    state_topic: "tele/dualschlaf/STATE"
    value_template:  "{{value_json.Uptime}}"

  - platform: mqtt
    name: Rollladen Schlafzimmer Version
    state_topic: "tele/dualschlaf/STATUS2"
    value_template:  "{{value_json['StatusFWR'].Version}}"
    
  - platform: mqtt
    name: Rollladen Schlafzimmer T1
    state_topic: "cmnd/swschlafex/POWER1"
    availability_topic: "tele/dualschlaf/LWT"

  - platform: mqtt
    name: Rollladen Schlafzimmer T2
    state_topic: "cmnd/swschlafex/POWER2"
    availability_topic: "tele/dualschlaf/LWT"


#Temperatur
  - platform: mqtt
    name: Sensor Schlafzimmer Wlan
    state_topic: "tele/tsensorschlaf/STATE"
    unit_of_measurement: "%"
    value_template:  "{{value_json['Wifi'].RSSI}}"
  - platform: mqtt
    state_topic: "tele/tsensorschlaf/STATE"
    name: Sensor Schlafzimmer SSId
    value_template:  "{{value_json['Wifi'].SSId}}"

  - platform: mqtt
    name: Sensor Schlafzimmer V
    state_topic: "tele/tsensorschlaf/STATE"
    unit_of_measurement: "V"
    value_template:  "{{value_json.Vcc}}"

  - platform: mqtt
    name: Sensor Schlafzimmer LZ
    state_topic: "tele/tsensorschlaf/STATE"
    value_template:  "{{value_json.Uptime}}"

  - platform: mqtt
    name: Sensor Schlafzimmer Version
    state_topic: "tele/tsensorschlaf/STATUS2"
    value_template:  "{{value_json['StatusFWR'].Version}}"
    
  - platform: mqtt
    name: Schlafzimmer Temperatur
    state_topic: "tele/tsensorschlaf/STATUS10"
    unit_of_measurement: "°C"
    value_template:  "{{(value_json.StatusSNS.HTU21.Temperature| float - 2.2)| round(1)}}"

  - platform: mqtt
    name: Schlafzimmer Feuchte
    state_topic: "tele/tsensorschlaf/STATUS10"
    unit_of_measurement: "%"
    value_template:  "{{(value_json.StatusSNS.HTU21.Humidity| float + 10.0)| round(1)}}"

cover:
  - platform: mqtt
    name: Rollladen Schlafzimmer
    state_topic: "home/dualschlaf/POWER"
    command_topic: "cmnd/dualschlaf/Backlog"
    availability_topic: "tele/dualschlaf/LWT"
    payload_open: "power1 ON"
    payload_close: "power2 ON"
    payload_stop: "power1 OFF;power2 OFF"
    qos: 1
    optimistic: false

history_graph:

  gr35:
    name: Schlafzimmer Graph
    entities:
     - sensor.schlafzimmer_temperatur
     - sensor.schlafzimmer_feuchte
    hours_to_show: 240
    refresh: 60

timer:
  rollladen_schlafzimmer_auf:
    name: Rollladen Schlafzimmer Auf
    duration: '00:00:20'
  rollladen_schlafzimmer_zu:
    name: Rollladen Schlafzimmer Zu
    duration: '00:00:20'
automation:


  - alias: Rollladen Schlafzimmer Auf Manuell
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.rollladen_schlafzimmer_t1
        to: "ON"
    action:
      - service: cover.open_cover
        entity_id: cover.rollladen_schlafzimmer
      - service: timer.start
        entity_id: timer.rollladen_schlafzimmer_auf
      - service: timer.stop
        entity_id: timer.rollladen_schlafzimmer_zu
      - service: mqtt.publish
        data:
          topic: "home/dualschlaf/POWER"
          payload: 'off'
          qos: 0
          retain: true

  - alias: Rollladen Schlafzimmer sind Auf
    initial_state: True
    trigger:
      platform: event
      event_type: timer.finished
      event_data: 
        entity_id: timer.rollladen_schlafzimmer_auf
    action:
      - service: timer.stop
        entity_id: timer.rollladen_schlafzimmer_auf
      - service: cover.stop_cover
        entity_id: cover.rollladen_schlafzimmer
      - service: mqtt.publish
        data:
          topic: "home/dualschlaf/POWER"
          payload: 'open'
          qos: 0
          retain: true


  - alias: Rollladen Schlafzimmer Zu Manuell
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.rollladen_schlafzimmer_t2
        to: "ON"
    action:
      - service: cover.close_cover
        entity_id: cover.rollladen_schlafzimmer
      - service: timer.start
        entity_id: timer.rollladen_schlafzimmer_zu
      - service: timer.stop
        entity_id: timer.rollladen_schlafzimmer_auf
      - service: mqtt.publish
        data:
          topic: "home/dualschlaf/POWER"
          payload: 'off'
          qos: 0
          retain: true

  - alias: Rollladen Schlafzimmer sind Zu
    initial_state: True
    trigger:
      platform: event
      event_type: timer.finished
      event_data: 
        entity_id: timer.rollladen_schlafzimmer_zu
    action:
      - service: timer.stop
        entity_id: timer.rollladen_schlafzimmer_zu
      - service: mqtt.publish
        data:
          topic: "home/dualschlaf/POWER"
          payload: 'closed'
          qos: 0
          retain: true
      - service: cover.stop_cover
        entity_id: cover.rollladen_schlafzimmer

  - alias: Rollladen Schlafzimmer stop Manuell
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.rollladen_schlafzimmer_t1
        to: "OFF"
      - platform: state
        entity_id: sensor.rollladen_schlafzimmer_t2
        to: "OFF"
    action:
      - service: cover.stop_cover
        entity_id: cover.rollladen_schlafzimmer
      - service: timer.pause
        entity_id: timer.rollladen_schlafzimmer_zu
      - service: timer.pause
        entity_id: timer.rollladen_schlafzimmer_auf

group:

  g_schlafzimmer_tracker:    
    name: Schlafzimmer Tracker
    entities:
    - device_tracker.dualschlaf
    - device_tracker.tsensorschlaf


  g_sz_schalter:
    name: Schlafzimmer Rolllade Schalter 
    view: no
    entities:
    - weblink.rollladen_schlafzimmer_web
    - cover.rollladen_schlafzimmer
    - switch.rollladen_schlafzimmer_dual
    - sensor.rollladen_schlafzimmer_wlan
    - timer.rollladen_schlafzimmer_auf
    - timer.rollladen_schlafzimmer_zu
    - sensor.rollladen_schlafzimmer_v
    - sensor.rollladen_schlafzimmer_lz
    - sensor.rollladen_schlafzimmer_t1
    - sensor.rollladen_schlafzimmer_t2

  g_sz_sensor:
    name: Schlafzimmer Sensor 
    view: no
    entities:
    - weblink.sensor_schlafzimmer_web
    - sensor.sensor_schlafzimmer_wlan
    - sensor.sensor_schlafzimmer_v
    - sensor.sensor_schlafzimmer_lz
    - sensor.schlafzimmer_temperatur
    - sensor.schlafzimmer_feuchte
    
  g_schlafzimmer:
    view: yes
    icon: mdi:sleep
    name: Schlafzimmer
    entities:
    - group.g_schlafzimmer_tracker
    - group.g_sz_schalter
    - group.g_sz_sensor
    - history_graph.schlafzimmer_graph




