
sensor:
  - platform: mqtt
    state_topic: "/home/tele/speicher_basteln/STATE"
    name: Speicher Schalter Basteln Wlan
    unit_of_measurement: "%"
    value_template:  "{{value_json['Wifi'].RSSI}}"

  - platform: mqtt
    name: Speicher Schalter Basteln V
    state_topic: "/home/tele/speicher_basteln/STATE"
    unit_of_measurement: "V"
    value_template:  "{{value_json.Vcc}}"

  - platform: mqtt
    name: Speicher Schalter Basteln LZ
    state_topic: "/home/tele/speicher_basteln/STATE"
    value_template:  "{{value_json.Uptime}}"

  - platform: mqtt
    name: Speicher Temperatur
    state_topic: "/home/tele/speicher_basteln/SENSOR"
    unit_of_measurement: "°C"
    value_template:  "{{value_json['HTU21'].Temperature}}"

  - platform: mqtt
    name: Speicher Feuchte
    state_topic: "/home/tele/speicher_basteln/SENSOR"
    unit_of_measurement: "%"
    value_template:  "{{value_json['HTU21'].Humidity}}"

history_graph:
  gr40:
    name: Speicher Graph
    entities:
     - sensor.speicher_temperatur
     - sensor.speicher_feuchte
    hours_to_show: 240
    refresh: 60

switch:
  - platform: mqtt
    name: Speicher Schalter Basteln
    state_topic: "/home/stat/speicher_basteln/POWER"
    command_topic: "/home/cmnd/speicher_basteln/POWER"
    availability_topic: "/home/tele/speicher_basteln/LWT"
    payload_available: "online"
    payload_not_available: "offline"
    qos: 1
    optimistic: false
    retain: true
#value_template: "{{ states('sensor.washing_machine_watts') | int < 3.4 }}"

automation:

  - alias: Speicher Schalter Basteln Aus
    trigger:
      - platform: state
        entity_id: switch.speicher_schalter_basteln
        to: "on"
        for:
          minutes: 60
    action:
      - service: switch.turn_off
        entity_id: switch.speicher_schalter_basteln


group:

  g_speicher_schalter:
    name: Gruppe Speicher Schalter Basteln 
    view: no
    entities:
    - weblink.speicher_schalter_basteln_web
    - switch.speicher_schalter_basteln
    - sensor.speicher_schalter_basteln_wlan
    - sensor.speicher_schalter_basteln_v
    - sensor.speicher_schalter_basteln_lz

  g_speicher_sensor:
    name: Sensor Speicher 
    view: no
    entities:
    - sensor.speicher_temperatur
    - sensor.speicher_feuchte

  g_speicher:
    name: Speicher
    icon: mdi:cursor-pointer
    view: yes
    entities:
    - group.g_speicher_sensor
    - group.g_speicher_schalter
#    - camera.buro
#    - group.g_bme280
    - history_graph.speicher_graph

