
sensor:
  - platform: mqtt
    state_topic: "tele/speicher_basteln/STATE"
    name: Speicher Schalter Basteln Wlan
    unit_of_measurement: "%"
    value_template:  "{{value_json['Wifi'].RSSI}}"
  - platform: mqtt
    state_topic: "tele/speicher_basteln/STATE"
    name: Speicher Schalter Basteln SSId
    value_template:  "{{value_json['Wifi'].SSId}}"

  - platform: mqtt
    name: Speicher Schalter Basteln V
    state_topic: "tele/speicher_basteln/STATE"
    unit_of_measurement: "V"
    value_template:  "{{value_json.Vcc}}"

  - platform: mqtt
    name: Speicher Schalter Basteln LZ
    state_topic: "tele/speicher_basteln/STATE"
    value_template:  "{{value_json.Uptime}}"

  - platform: mqtt
    name: Speicher Schalter Basteln Version
    state_topic: "tele/speicher_basteln/STATUS2"
    value_template:  "{{value_json.StatusFWR.Version}}"
    
  - platform: mqtt
    name: Speicher Temperatur
    state_topic: "tele/speicher_basteln/STATUS10"
    unit_of_measurement: "°C"
    value_template:  "{{(value_json.StatusSNS.HTU21.Temperature| float - 0.5)| round(1)}}"

  - platform: mqtt
    name: Speicher Feuchte
    state_topic: "tele/speicher_basteln/STATUS10"
    unit_of_measurement: "%"
    value_template:  "{{(value_json.StatusSNS.HTU21.Humidity| float + 6.7)| round(1)}}"

history_graph:
  gr40:
    name: Speicher Graph
    entities:
     - sensor.speicher_temperatur
     - sensor.speicher_feuchte
    hours_to_show: 240
    refresh: 60

switch:
  - platform: mqtt
    name: Speicher Schalter Basteln
    state_topic: "stat/speicher_basteln/POWER"
    command_topic: "cmnd/speicher_basteln/POWER"
    availability_topic: "tele/speicher_basteln/LWT"
    qos: 1
    optimistic: false
    retain: true

automation:

  - alias: Speicher Schalter Basteln Aus
    initial_state: True
    trigger:
      - platform: state
        entity_id: switch.speicher_schalter_basteln
        to: "on"
        for:
          minutes: 60
    action:
      - service: switch.turn_off
        entity_id: switch.speicher_schalter_basteln
      - service: notify.wolfgang
        data:
         title: '*Schalter Basteln*'
         message: ' Aus nach Zeit' 


group:
  g_speicher_tracker:    
    name: Speicher Tracker 
    view: no
    entities:
    - device_tracker.speicherbasteln

  g_speicher_schalter:
    name: Gruppe Speicher Schalter Basteln 
    view: no
    entities:
    - weblink.speicher_schalter_basteln_web
    - switch.speicher_schalter_basteln
    - sensor.speicher_schalter_basteln_wlan
    - sensor.speicher_schalter_basteln_v
    - sensor.speicher_schalter_basteln_lz

  g_speicher_sensor:
    name: Sensor Speicher 
    view: no
    entities:
    - sensor.speicher_temperatur
    - sensor.speicher_feuchte

  g_speicher:
    name: Speicher
    icon: mdi:cursor-pointer
    view: yes
    entities:
    - group.g_speicher_tracker
    - group.g_speicher_sensor
    - group.g_speicher_schalter
    - history_graph.speicher_graph

