switch:
  - platform: mqtt
    name: Test Schalter 
    state_topic: "stat/sonoff/POWER"
    command_topic: "cmnd/sonoff/POWER"
    availability_topic: "tele/sonoff/LWT"
    qos: 1
    optimistic: false
    retain: true

binary_sensor:
  - platform: mqtt
    name: Test Schalter Taste
    state_topic: "cmnd/sonoffex/POWER1"

sensor:
  - platform: mqtt
    name: Test Schalter Wlan
    state_topic: "tele/sonoff/STATE"
    unit_of_measurement: "%"
    value_template:  "{{value_json['Wifi'].RSSI}}"

  - platform: mqtt
    name: Test Schalter V
    state_topic: "tele/sonoff/STATE"
    unit_of_measurement: "V"
    value_template:  "{{value_json.Vcc}}"

  - platform: mqtt
    name: Test Schalter LZ
    state_topic: "tele/sonoff/STATE"
    value_template:  "{{value_json.Uptime}}"

  - platform: mqtt
    name: Test Schalter Temperatur
    state_topic: "tele/sonoff/SENSOR"
    unit_of_measurement: "°C"
    value_template:  "{{value_json['HTU21'].Temperature}}"

  - platform: mqtt
    name: Test Schalter Feuchte
    state_topic: "tele/sonoff/SENSOR"
    unit_of_measurement: "%"
    value_template:  "{{value_json['HTU21'].Humidity}}"

history_graph:
  grtest:
    name: Test Graph
    entities:
    - sensor.test_schalter_temperatur
    - sensor.test_schalter_feuchte
    hours_to_show: 240
    refresh: 60

group:
  g_test_schalter:
    name: Test Schalter
    entities:
    - weblink.test_schalter_web
    - switch.test_schalter
    - sensor.test_schalter_wlan
    - sensor.test_schalter_v
    - sensor.test_schalter_lz
    - binary_sensor.test_schalter_taste
  g_test_sensor:
    name: Sensor Test 
    view: no
    entities:
    - sensor.test_schalter_temperatur
    - sensor.test_schalter_feuchte

  g_test:
    name: test
    view: yes
    entities:
    - group.g_test_schalter
    - group.g_test_sensor
    - history_graph.test_graph
