switch:
  - platform: mqtt
    name: Test Schalter 
    state_topic: "/home/stat/sonoff/POWER"
    command_topic: "/home/cmnd/sonoff/POWER"
    availability_topic: "/home/tele/sonoff/LWT"
    qos: 1
    optimistic: false
    retain: true

binary_sensor:
  - platform: mqtt
    name: Test Schalter Taste
    state_topic: "/home/cmnd/sonoffex/POWER1"

sensor:
  - platform: mqtt
    name: Test Schalter Wlan
    state_topic: "/home/tele/sonoff/STATE"
    unit_of_measurement: "%"
    value_template:  "{{value_json['Wifi'].RSSI}}"

  - platform: mqtt
    name: Test Schalter V
    state_topic: "/home/tele/sonoff/STATE"
    unit_of_measurement: "V"
    value_template:  "{{value_json.Vcc}}"

  - platform: mqtt
    name: Test Schalter LZ
    state_topic: "/home/tele/sonoff/STATE"
    value_template:  "{{value_json.Uptime}}"

  - platform: mqtt
    name: Test Schalter Temperatur
    state_topic: "/home/tele/sonoff/SENSOR"
    unit_of_measurement: "°C"
    value_template:  "{{value_json['HTU21'].Temperature}}"

  - platform: mqtt
    name: Test Schalter Feuchte
    state_topic: "/home/tele/sonoff/SENSOR"
    unit_of_measurement: "%"
    value_template:  "{{value_json['HTU21'].Humidity}}"


group:
  g_test_schalter:
    name: Test Schalter
    entities:
    - weblink.licht_keller_flur_web
    - switch.test_schalter
    - sensor.test_schalter_wlan
    - sensor.test_schalter_v
    - sensor.test_schalter_lz
    - binary_sensor.test_schalter_taste
  g_test_sensor:
    name: Sensor Oben 
    view: no
    entities:
    - sensor.schalter_temperatur
    - sensor.schalter_feuchte

  g_test:
    name: test
    view: yes
    entities:
    - group.g_test_schalter
    - group.g_test_sensor
    - history_graph.oben_graph
