sensor:
  - platform: mqtt
    state_topic: "tele/l_schalter_vor/STATE"
    name: Lade Schalter Vorrat Wlan
    unit_of_measurement: "%"
    value_template:  "{{value_json['Wifi'].RSSI}}"
  - platform: mqtt
    state_topic: "tele/l_schalter_vor/STATE"
    name: Lade Schalter Vorrat SSId
    value_template:  "{{value_json['Wifi'].SSId}}"

  - platform: mqtt
    name: Lade Schalter Vorrat V
    state_topic: "tele/l_schalter_vor/STATE"
    unit_of_measurement: "V"
    value_template:  "{{value_json.Vcc}}"

  - platform: mqtt
    name: Lade Schalter Vorrat LZ
    state_topic: "tele/l_schalter_vor/STATE"
    value_template:  "{{value_json.Uptime}}"

  - platform: mqtt
    name: Lade Schalter Vorrat Version
    state_topic: "tele/l_schalter_vor/STATUS2"
    value_template:  "{{value_json['StatusFWR'].Version}}"
    
  - platform: mqtt
    name: Vorrat Temperatur
    state_topic: "tele/l_schalter_vor/STATUS10"
    unit_of_measurement: "°C"
    value_template:  "{{(value_json.StatusSNS.HTU21.Temperature| float - 2.0)| round(1)}}"

  - platform: mqtt
    name: Vorrat Feuchte
    state_topic: "tele/l_schalter_vor/STATUS10"
    unit_of_measurement: "%"
    value_template:  "{{(value_json.StatusSNS.HTU21.Humidity| float + 10.0)| round(1)}}"

binary_sensor:   
  - platform: mqtt
    name: "Haustuer Kontakt"
    state_topic: 'home/OpenDoorHaus'
    payload_on: 'on'
    payload_off: 'off'
    device_class: door
    
  - platform: mqtt
    name: "Treppenfenster Kontakt"
    state_topic: 'home/OpenFensterTreppe'
    payload_on: 'on'
    payload_off: 'off'
    device_class: window
    
  - platform: mqtt
    name: "WC Fenster Kontakt"
    state_topic: 'home/OpenFensterWc'
    payload_on: 'on'
    payload_off: 'off'
    device_class: window

  - platform: mqtt
    name: "Vorratsfenster Kontakt"
    state_topic: 'home/OpenFensterVorrat'
    payload_on: 'on'
    payload_off: 'off'
    device_class: window
   
switch:
  - platform: mqtt
    name: Lade Schalter Vorrat
    state_topic: "tele/l_schalter_vor/POWER"
    command_topic: "cmnd/l_schalter_vor/POWER"
    availability_topic: "tele/l_schalter_vor/LWT"
    qos: 1
    optimistic: false
    retain: true

history_graph:
  gr20:
    name: Unten Graph
    entities:
    - sensor.kueche_temperatur
    - sensor.kueche_feuchte
    - sensor.wohnzimmer_temperatur
    - sensor.wohnzimmer_feuchte
    - sensor.vorrat_temperatur
    - sensor.vorrat_feuchte
    hours_to_show: 240
    refresh: 60

automation:


  - alias: Lade Schalter an
    trigger:
      platform: sun
      event: sunrise
    action:
      - service: switch.turn_on
        entity_id: switch.lade_schalter_vorrat
      

  - alias: Lade Schalter aus
    trigger:
      platform: sun
      event: sunset
    action:
      - service: switch.turn_off
        entity_id: switch.lade_schalter_vorrat


group:

  g_unten_tracker:    
    name: Unten Tracker
    entities:
    - device_tracker.lschaltervor

  g_lade_schalter_vorrat:
    name: Gruppe Lade Schalter Vorrat 
    view: no
    entities:
    - weblink.lade_schalter_vorrat_web
    - switch.lade_schalter_vorrat
    - sensor.lade_schalter_vorrat_wlan
    - sensor.lade_schalter_vorrat_v
    - sensor.lade_schalter_vorrat_lz

  g_unten_sensor:
    name: Unten Sensor
    view: no
    entities:
    - sensor.kueche_temperatur
    - sensor.kueche_feuchte
    - sensor.wohnzimmer_temperatur
    - sensor.wohnzimmer_feuchte
    - sensor.vorrat_temperatur
    - sensor.vorrat_feuchte
    - binary_sensor.haustuer_kontakt
    - binary_sensor.haustuer_kontakt_batt
    - binary_sensor.treppenfenster_kontakt
    - binary_sensor.treppenfenster_kontakt_batt
    - binary_sensor.wc_fenster_kontakt
    - binary_sensor.wc_fenster_kontakt_batt
    - binary_sensor.vorratsfenster_kontakt
    - binary_sensor.vorratsfenster_kontakt_batt

  g_unten:
    view: yes
    name: Unten
    entities:
    - group.g_unten_tracker
    - group.g_kueche
    - group.g_lade_schalter_vorrat
    - group.g_unten_sensor
    - history_graph.unten_graph
