sensor:
  - platform: mqtt
    state_topic: "tele/l_schalter_vor/STATE"
    name: Lade Schalter Vorrat Wlan
    unit_of_measurement: "%"
    value_template:  "{{value_json['Wifi'].RSSI}}"
  - platform: mqtt
    state_topic: "tele/l_schalter_vor/STATE"
    name: Lade Schalter Vorrat SSId
    value_template:  "{{value_json['Wifi'].SSId}}"

  - platform: mqtt
    name: Lade Schalter Vorrat V
    state_topic: "tele/l_schalter_vor/STATE"
    unit_of_measurement: "V"
    value_template:  "{{value_json.Vcc}}"

  - platform: mqtt
    name: Lade Schalter Vorrat LZ
    state_topic: "tele/l_schalter_vor/STATE"
    value_template:  "{{value_json.Uptime}}"

  - platform: mqtt
    name: Lade Schalter Vorrat Version
    state_topic: "tele/l_schalter_vor/STATUS2"
    value_template:  "{{value_json['StatusFWR'].Version}}"
    
  - platform: mqtt
    name: Vorrat Temperatur
    state_topic: "tele/l_schalter_vor/STATUS10"
    unit_of_measurement: "°C"
    value_template:  "{{(value_json.StatusSNS.HTU21.Temperature| float - 2.0)| round(1)}}"

  - platform: mqtt
    name: Vorrat Feuchte
    state_topic: "tele/l_schalter_vor/STATUS10"
    unit_of_measurement: "%"
    value_template:  "{{(value_json.StatusSNS.HTU21.Humidity| float + 10.0)| round(1)}}"

binary_sensor:   
  - platform: mqtt
    name: "Tuer Contact Haus"
    state_topic: 'home/OpenDoorHaus'
    payload_on: 'on'
    payload_off: 'off'
    device_class: door
    
  - platform: mqtt
    name: "Fenster Contact Treppe"
    state_topic: 'home/OpenFensterTreppe'
    payload_on: 'on'
    payload_off: 'off'
    device_class: window
    
  - platform: mqtt
    name: "Fenster Contact WC"
    state_topic: 'home/OpenFensterWc'
    payload_on: 'on'
    payload_off: 'off'
    device_class: window

  - platform: mqtt
    name: "Fenster Contact Vorrat"
    state_topic: 'home/OpenFensterVorrat'
    payload_on: 'on'
    payload_off: 'off'
    device_class: window
    
  - platform: mqtt
    name: "Tuer Contact Haus Alarm"
    state_topic: "tele/rfbridge/RFRECEIVED"
    payload_on: "02F90B"
    payload_off: "02F907"
    qos: 0
    device_class: battery
    value_template: '{{ value_json.RfReceived.Data }}'


    
  - platform: mqtt
    name: "Fenster Contact Treppe Alarm"
    state_topic: "tele/rfbridge/RFRECEIVED"
    payload_on: "290DEB"
    payload_off: "290DE7"
    qos: 0
    device_class: battery
    value_template: '{{ value_json.RfReceived.Data }}'

    
  - platform: mqtt
    name: "Fenster Contact Wc Alarm"
    state_topic: "tele/rfbridge/RFRECEIVED"
    payload_on: "5E63EB"
    payload_off: "5E63E7"
    qos: 0
    device_class: battery
    value_template: '{{ value_json.RfReceived.Data }}'

    
  - platform: mqtt
    name: "Fenster Contact Vorrat Alarm"
    state_topic: "tele/rfbridge/RFRECEIVED"
    payload_on: "A805EB"
    payload_off: "A805E7"
    qos: 0
    device_class: battery
    value_template: '{{ value_json.RfReceived.Data }}'

    
switch:
  - platform: mqtt
    name: Lade Schalter Vorrat
    state_topic: "tele/l_schalter_vor/POWER"
    command_topic: "cmnd/l_schalter_vor/POWER"
    availability_topic: "tele/l_schalter_vor/LWT"
    qos: 1
    optimistic: false
    retain: true

history_graph:
  gr20:
    name: Unten Graph
    entities:
    - sensor.kueche_temperatur
    - sensor.kueche_feuchte
    - sensor.wohnzimmer_temperatur
    - sensor.wohnzimmer_feuchte
    - sensor.vorrat_temperatur
    - sensor.vorrat_feuchte
    hours_to_show: 240
    refresh: 60

automation:


  - alias: Lade Schalter an
    trigger:
      platform: sun
      event: sunrise
    action:
      - service: switch.turn_on
        entity_id: switch.lade_schalter_vorrat
      

  - alias: Lade Schalter aus
    trigger:
      platform: sun
      event: sunset
    action:
      - service: switch.turn_off
        entity_id: switch.lade_schalter_vorrat

  - alias: OpenDoorHausON
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.rf_bridge_result
        to: '02F90E'
    action:
      - service: mqtt.publish
        data:
          topic: "home/OpenDoorHaus"
          payload: 'on'
          qos: 0
          retain: true
          
  - alias: OpenDoorHausOff
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.rf_bridge_result
        to: '02F907'
    action:
      - service: mqtt.publish
        data:
          topic: "home/OpenDoorHaus"
          payload: 'off'
          qos: 0
          retain: true
    

  - alias: OpenFensterTreppeON
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.rf_bridge_result
        to: '290DEE'
    action:
      - service: mqtt.publish
        data:
          topic: "home/OpenFensterTreppe"
          payload: 'on'
          qos: 0
          retain: true
  - alias: OpenFensterTreppeOff
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.rf_bridge_result
        to: '290DE7'
    action:
      - service: mqtt.publish
        data:
          topic: "home/OpenFensterTreppe"
          payload: 'off'
          qos: 0
          retain: true

  - alias: OpenFensterWcON
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.rf_bridge_result
        to: '5E63EE'
    action:
      - service: mqtt.publish
        data:
          topic: "home/OpenFensterWc"
          payload: 'on'
          qos: 0
          retain: true
  - alias: OpenFensterWcOff
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.rf_bridge_result
        to: '5E63E7'
    action:
      - service: mqtt.publish
        data:
          topic: "home/OpenFensterWc"
          payload: 'off'
          qos: 0
          retain: true
          
  - alias: OpenFensterVorratON
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.rf_bridge_result
        to: 'A805EE'
    action:
      - service: mqtt.publish
        data:
          topic: "home/OpenFensterVorrat"
          payload: 'on'
          qos: 0
          retain: true
  - alias: OpenFensterVorratOff
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.rf_bridge_result
        to: 'A805E7'
    action:
      - service: mqtt.publish
        data:
          topic: "home/OpenFensterVorrat"
          payload: 'off'
          qos: 0
          retain: true

group:

  g_unten_tracker:    
    name: Unten Tracker
    entities:
    - device_tracker.lschaltervor

  g_lade_schalter_vorrat:
    name: Gruppe Lade Schalter Vorrat 
    view: no
    entities:
    - weblink.lade_schalter_vorrat_web
    - switch.lade_schalter_vorrat
    - sensor.lade_schalter_vorrat_wlan
    - sensor.lade_schalter_vorrat_v
    - sensor.lade_schalter_vorrat_lz

  g_unten_sensor:
    name: Unten Sensor
    view: no
    entities:
    - sensor.kueche_temperatur
    - sensor.kueche_feuchte
    - sensor.wohnzimmer_temperatur
    - sensor.wohnzimmer_feuchte
    - sensor.vorrat_temperatur
    - sensor.vorrat_feuchte
    - binary_sensor.tuer_contact_kueche
    - binary_sensor.tuer_contact_kueche_alarm
    - binary_sensor.tuer_contact_haus
    - binary_sensor.tuer_contact_haus_alarm
    - binary_sensor.fenster_contact_kueche
    - binary_sensor.fenster_contact_kueche_alarm
    - binary_sensor.fenster_contact_treppe
    - binary_sensor.fenster_contact_treppe_alarm
    - binary_sensor.fenster_contact_wc
    - binary_sensor.fenster_contact_wc_alarm
    - binary_sensor.fenster_contact_vorrat
    - binary_sensor.fenster_contact_vorrat_alarm

  g_unten:
    view: yes
    name: Unten
    entities:
    - group.g_unten_tracker
    - group.g_kueche
    - group.g_lade_schalter_vorrat
    - group.g_unten_sensor
    - history_graph.unten_graph
