input_boolean:
  boolean_urlaub:
    name: Urlaub
    
automation:

  - alias: Urlaub Ein
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_urlaub
        from: 'off'
        to: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: automation.radio_an_werktags
      - service: homeassistant.turn_off
        entity_id: automation.kaffee_an_werktags
      - service: homeassistant.turn_off
        entity_id: automation.kaffee_an
      - service: homeassistant.turn_off
        entity_id: automation.lade_schalter_an
  - alias: Urlaub Aus
    trigger:
      - platform: state
        entity_id: input_boolean.boolean_urlaub
        from: 'on'
        to: 'off'

    action:
      - service: homeassistant.turn_on
        entity_id: automation.radio_an_werktags
      - service: homeassistant.turn_on
        entity_id: automation.kaffee_an_werktags
      - service: homeassistant.turn_on
        entity_id: automation.kaffee_an
      - service: homeassistant.turn_on
        entity_id: automation.lade_schalter_an
 